import useTimeStore from "@/store/store";

const useZustandState = () => {
  const {
    play,
    pomodoroType,
    setBreak,
    setFocus,
    setTime,
    status,
    decreaseFocusTime,
    focusTime,
    pause,
    increaseGoal,
    increaseRound,
    roundEnd,
    roundStart,
    goalEnd,
    goalStart,
    setGoal,
    setRound,
    alarmControl,
    closeModal,
    isAlarmOn,
    isShowModal,
    isTikTokOn,
    showModal,
    tikTokControl,
    closeInfoPanel,
    isInfoPanelShow,
    showInfoPanel,
  } = useTimeStore((state) => ({
    pomodoroType: state.pomodoroType,
    setFocus: state.setFocusSession,
    setBreak: state.setShortBreak,
    setTime: state.setPomodoroTime,
    status: state.playStatus,
    play: state.playAction,
    pause: state.pauseAction,
    focusTime: state.focusTime,
    decreaseFocusTime: state.decreaseFocusTime,
    roundStart: state.roundStart,
    roundEnd: state.roundEnd,
    goalStart: state.goalStart,
    goalEnd: state.goalEnd,
    increaseRound: state.increaseRound,
    increaseGoal: state.increaseGoal,
    setRound: state.setRound,
    setGoal: state.setGoal,
    isAlarmOn: state.isAlarmOn,
    isTikTokOn: state.isTikTokOn,
    alarmControl: state.alarmControl,
    tikTokControl: state.tikTokControl,
    isShowModal: state.isShowModal,
    showModal: state.showModal,
    closeModal: state.closeModal,
    isInfoPanelShow: state.isInfoPanelShow,
    showInfoPanel: state.showInfoPanel,
    closeInfoPanel: state.closeInfoPanel,
  }));

  return {
    play,
    pomodoroType,
    setBreak,
    setFocus,
    setTime,
    status,
    decreaseFocusTime,
    focusTime,
    pause,
    increaseGoal,
    increaseRound,
    roundEnd,
    roundStart,
    goalEnd,
    goalStart,
    setRound,
    setGoal,
    alarmControl,
    closeModal,
    isAlarmOn,
    isShowModal,
    isTikTokOn,
    showModal,
    tikTokControl,
    isInfoPanelShow,
    showInfoPanel,
    closeInfoPanel,
  };
};

export default useZustandState;
